Adicionando uma licença para o projeto
RGivisiez/Colab pull request #1
Opened 2020-08-26 13:30 UTC by RGivisiez

Adicionei a licença mais comum de todas, a MIT. Basicamente, ela permite qualquer usar, para o que bem entender, os programas desse repositório.

2020-08-26 22:13 UTC, RGivisiez commented
Essa aqui é a área de comentários do pull request que fiz @Leo-am. Acho que se você for na aba de Files changed dá para comentar ou até editar o meu código, mas não tenho certeza.

2020-08-26 23:24 UTC, Leo-am commented on LICENSE
> +The above copyright notice and this permission notice shall be included in all
Testando comentários em múltiplas linhas.

2020-08-26 23:25 UTC, Leo-am requested changes
Tô pedindo uma mudança só para ver como funciona.

2020-08-26 23:34 UTC, RGivisiez commented on LICENSE
> +The above copyright notice and this permission notice shall be included in all
Testando add single comment

2020-08-26 23:34 UTC, RGivisiez commented on LICENSE
> +The above copyright notice and this permission notice shall be included in all
Testando review

2020-08-26 23:35 UTC, RGivisiez commented on LICENSE
> +The above copyright notice and this permission notice shall be included in all
Quando você deixa um comentário de Review, uma tag Pending aparece.

2020-08-27 02:39 UTC, Leo-am approved these changes
Agora sim, muito melhor.

2020-08-27 02:40 UTC, merged